version: '3'
services:
  rtmp:
    image: alfg/nginx-rtmp
    ports:
     - "80:80"
     - "1935:1935"
    links:
     - site
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
     - ./site:/var/site
    depends_on:
     - site
  site:
    image: node:12
    working_dir: /var/www
    command: ['node', 'index.js']
    expose:
     - "8080"
    volumes:
     - ./site:/var/www:ro
